packages:
  - "apps/*"
  - "packages/*"
  - "packages/integrations/*"
allowBuilds:
  esbuild: true
  lefthook: true
  sharp: true
  workerd: true
patchedDependencies:
  next-auth@5.0.0-beta.25: patches/next-auth@5.0.0-beta.25.patch
