// UBM Hyogo member site - seed data

const SURVEY_SECTIONS = [
  {
    key: "basic_profile",
    label: "基本プロフィール",
    note: "公開プロフィールの基礎情報",
    fields: [
      { key: "fullName", label: "お名前", kind: "shortText", required: true, visibility: "public" },
      { key: "nickname", label: "ニックネーム", kind: "shortText", required: false, visibility: "public" },
      { key: "location", label: "お住まい", kind: "shortText", required: true, visibility: "public" },
      { key: "birthDate", label: "生年月日", kind: "date", required: false, visibility: "member" },
      { key: "occupation", label: "職業・仕事内容", kind: "shortText", required: true, visibility: "public" },
      { key: "hometown", label: "出身地", kind: "shortText", required: false, visibility: "public" },
    ],
  },
  {
    key: "ubm_profile",
    label: "UBM情報",
    note: "会区画と参加経緯",
    fields: [
      { key: "ubmZone", label: "UBM区画", kind: "radio", required: true, visibility: "public", options: ["0→1", "1→10", "10→100"] },
      { key: "ubmMembershipType", label: "UBM参加ステータス", kind: "radio", required: true, visibility: "public", options: ["会員", "非会員", "アカデミー生"] },
      { key: "ubmJoinDate", label: "UBM参加時期", kind: "shortText", required: false, visibility: "member" },
      { key: "businessOverview", label: "ビジネス概要", kind: "paragraph", required: true, visibility: "public" },
      { key: "skills", label: "得意分野・スキル", kind: "paragraph", required: false, visibility: "public" },
      { key: "challenges", label: "現在の課題", kind: "paragraph", required: false, visibility: "member" },
      { key: "canProvide", label: "提供できること", kind: "paragraph", required: false, visibility: "public" },
    ],
  },
  {
    key: "personal_profile",
    label: "パーソナル",
    note: "人柄と関心の見え方",
    fields: [
      { key: "hobbies", label: "趣味・好きなこと", kind: "shortText", required: false, visibility: "public" },
      { key: "recentInterest", label: "最近ハマっていること", kind: "shortText", required: false, visibility: "public" },
      { key: "motto", label: "座右の銘", kind: "shortText", required: false, visibility: "public" },
      { key: "otherActivities", label: "仕事以外の活動", kind: "paragraph", required: false, visibility: "public" },
    ],
  },
  {
    key: "social_links",
    label: "SNS・Web",
    note: "公開リンク群",
    fields: [
      { key: "urlWebsite", label: "Webサイト", kind: "url", required: false, visibility: "public" },
      { key: "urlX", label: "X", kind: "url", required: false, visibility: "public" },
      { key: "urlInstagram", label: "Instagram", kind: "url", required: false, visibility: "public" },
      { key: "urlFacebook", label: "Facebook", kind: "url", required: false, visibility: "public" },
      { key: "urlLinkedin", label: "LinkedIn", kind: "url", required: false, visibility: "public" },
      { key: "urlNote", label: "note", kind: "url", required: false, visibility: "public" },
      { key: "urlYoutube", label: "YouTube", kind: "url", required: false, visibility: "public" },
      { key: "urlThreads", label: "Threads", kind: "url", required: false, visibility: "public" },
      { key: "urlTiktok", label: "TikTok", kind: "url", required: false, visibility: "public" },
    ],
  },
  {
    key: "message",
    label: "メッセージ",
    note: "一言自己紹介",
    fields: [
      { key: "selfIntroduction", label: "自己紹介", kind: "paragraph", required: false, visibility: "public" },
    ],
  },
  {
    key: "consent",
    label: "同意",
    note: "公開と利用の可否",
    fields: [
      { key: "publicConsent", label: "ホームページ掲載に同意", kind: "radio", required: true, visibility: "admin", options: ["同意する", "同意しない"] },
      { key: "ruleConsent", label: "勧誘ルール・免責事項への同意", kind: "radio", required: true, visibility: "admin", options: ["同意する", "同意しない"] },
    ],
  },
];

const TAG_CATALOG = [
  { category: "ビジネス・経営", tags: ["経営者・代表", "事業開発", "経営戦略", "人事・採用", "財務・会計"] },
  { category: "IT・テクノロジー", tags: ["エンジニア", "Web・IT", "DX推進", "AI・データ", "UI/UX"] },
  { category: "クリエイティブ", tags: ["デザイン", "動画・映像", "写真", "コンテンツ制作", "ライター・編集"] },
  { category: "マーケティング", tags: ["マーケティング", "SNS運用", "ブランディング", "営業・販売", "広告運用"] },
  { category: "専門職", tags: ["士業", "医療・福祉", "教育・コーチング", "金融・保険", "研究・学術"] },
  { category: "ライフスタイル", tags: ["飲食・食品", "美容・健康", "不動産", "旅行・観光", "製造業"] },
];

const ALL_TAGS = TAG_CATALOG.flatMap(g => g.tags);

const MEETINGS = [
  { id: "meet-2026-04", date: "2026-04-09", label: "2026年4月支部会", note: "プロフィール共有会", attendees: 28 },
  { id: "meet-2026-03", date: "2026-03-12", label: "2026年3月支部会", note: "AI活用の事例共有", attendees: 24 },
  { id: "meet-2026-02", date: "2026-02-15", label: "2026年2月定例会", note: "新年度キックオフ", attendees: 31 },
  { id: "meet-2026-01", date: "2026-01-16", label: "2026年1月新年会", note: "懇親会中心", attendees: 26 },
  { id: "meet-2025-12", date: "2025-12-11", label: "2025年12月支部会", note: "1年振り返り", attendees: 22 },
];

const MEMBERS = [
  {
    id: "m1", responseId: "resp-001", email: "taro@example.com", submittedAt: "2026-03-28 09:12",
    fullName: "山田 太郎", nickname: "タロー", location: "兵庫県神戸市", birthDate: "1987-02-14",
    hometown: "兵庫県明石市", occupation: "生成AIコンサルタント", ubmZone: "1→10", ubmMembershipType: "会員",
    ubmJoinDate: "2024年10月",
    businessOverview: "中小企業向けに生成AIの導入と業務改善の伴走支援を提供。社内データを活用した業務自動化の設計から、現場への定着まで一貫して支援します。",
    skills: "プロンプト設計 / 業務整理 / AI研修", challenges: "継続案件化と採用広報",
    canProvide: "AI活用設計、生成AI研修、社内導入支援", hobbies: "珈琲, カメラ, 旅行",
    recentInterest: "音声AIと業務自動化", motto: "まず試してから整える",
    otherActivities: "地元の創業支援イベントでAI勉強会を企画。",
    urlWebsite: "https://example.com/taro", urlX: "https://x.com/example_taro",
    urlNote: "https://note.com/example_taro", urlLinkedin: "https://linkedin.com/in/exampletaro",
    urlInstagram: "https://instagram.com/example.taro",
    selfIntroduction: "兵庫の事業者同士が自然につながる場づくりに関心があります。",
    publicConsent: "同意する", ruleConsent: "同意する",
    tags: ["AI・データ", "DX推進", "経営者・代表"], isPublic: true, isDeleted: false,
    attendance: ["meet-2026-02", "meet-2026-03", "meet-2026-04"],
    updatedAt: "2026-04-09 09:30", hue: 0,
  },
  {
    id: "m2", responseId: "resp-002", email: "hana@example.com", submittedAt: "2026-03-29 11:40",
    fullName: "鈴木 花子", nickname: "ハナ", location: "兵庫県西宮市", birthDate: "1990-09-03",
    hometown: "大阪府堺市", occupation: "ブランドデザイナー", ubmZone: "0→1", ubmMembershipType: "アカデミー生",
    ubmJoinDate: "2025年7月",
    businessOverview: "中小企業やスモールブランドのトーン設計からLP改善まで一気通貫で支援するデザイナーです。",
    skills: "UIデザイン / ブランディング / 写真ディレクション", challenges: "案件単価の再設計",
    canProvide: "デザインレビュー、写真ディレクション、LP改善", hobbies: "読書, 展示会, ランニング",
    recentInterest: "商品撮影のライティング", motto: "伝わるまで整える",
    otherActivities: "地域のアートイベント運営に参加。",
    urlWebsite: "https://example.com/hanako", urlInstagram: "https://instagram.com/example.hanako",
    urlNote: "https://note.com/example_hanako", urlThreads: "https://threads.net/@example.hanako",
    selfIntroduction: "視覚整理で、伝わりにくい価値を伝わる形に変えるのが得意です。",
    publicConsent: "同意する", ruleConsent: "同意する",
    tags: ["デザイン", "ブランディング", "UI/UX"], isPublic: true, isDeleted: false,
    attendance: ["meet-2026-03", "meet-2026-04"],
    updatedAt: "2026-04-08 20:10", hue: 1,
  },
  {
    id: "m3", responseId: "resp-003", email: "koichi@example.com", submittedAt: "2026-03-27 15:05",
    fullName: "中村 恒一", nickname: "コウイチ", location: "兵庫県姫路市", birthDate: "1980-11-21",
    hometown: "岡山県倉敷市", occupation: "司法書士", ubmZone: "10→100", ubmMembershipType: "会員",
    ubmJoinDate: "2023年4月",
    businessOverview: "事業再編や契約実務を中心に、経営者向けに法務相談を提供しています。M&Aや事業承継の実績多数。",
    skills: "契約実務 / 事業承継 / 法務相談", challenges: "オンライン発信の強化",
    canProvide: "契約レビュー、事業相談、法務セミナー", hobbies: "庭仕事, 将棋",
    recentInterest: "事業承継の相談対応", motto: "誠実さは最強の営業",
    otherActivities: "学校でのキャリア授業に協力。",
    urlWebsite: "https://example.com/nakamura", urlX: "https://x.com/example_nakamura",
    urlLinkedin: "https://linkedin.com/in/example-nakamura",
    selfIntroduction: "安心してつながれる場づくりを重視しています。",
    publicConsent: "同意しない", ruleConsent: "同意する",
    tags: ["士業", "経営戦略"], isPublic: false, isDeleted: false,
    attendance: ["meet-2026-02", "meet-2026-03"],
    updatedAt: "2026-04-01 11:45", hue: 2,
  },
  {
    id: "m4", responseId: "resp-004", email: "aya@example.com", submittedAt: "2026-03-30 08:22",
    fullName: "佐藤 彩", nickname: "あや", location: "兵庫県芦屋市", birthDate: "1985-06-18",
    hometown: "京都府京都市", occupation: "SaaSプロダクトマネージャー", ubmZone: "1→10", ubmMembershipType: "会員",
    ubmJoinDate: "2024年2月",
    businessOverview: "BtoB SaaS のプロダクト企画と顧客成功を横断的に担当。小さなチームでの機能企画からリリース運用まで。",
    skills: "プロダクト設計 / ユーザーインタビュー / ロードマップ策定",
    challenges: "営業組織とのハンドオフ設計",
    canProvide: "プロダクト壁打ち、ユーザーインタビュー設計",
    hobbies: "ヨガ, 陶芸", recentInterest: "オンボーディング設計", motto: "小さく出して早く直す",
    urlWebsite: "https://example.com/aya", urlX: "https://x.com/example_aya",
    urlLinkedin: "https://linkedin.com/in/example-aya",
    selfIntroduction: "仕組みづくりと実験を行き来するのが好きです。",
    publicConsent: "同意する", ruleConsent: "同意する",
    tags: ["Web・IT", "UI/UX", "事業開発"], isPublic: true, isDeleted: false,
    attendance: ["meet-2026-03", "meet-2026-04"], updatedAt: "2026-04-07 18:22", hue: 3,
  },
  {
    id: "m5", responseId: "resp-005", email: "kenji@example.com", submittedAt: "2026-03-31 19:40",
    fullName: "井上 健司", nickname: "ケン", location: "兵庫県尼崎市", birthDate: "1978-03-30",
    hometown: "兵庫県尼崎市", occupation: "町工場3代目・製造業", ubmZone: "10→100", ubmMembershipType: "会員",
    ubmJoinDate: "2022年9月",
    businessOverview: "精密板金加工を手がける町工場の3代目として、既存事業のデジタル化と新規市場開拓を推進。",
    skills: "製造業DX / 生産管理 / 取引先開拓",
    challenges: "若手採用と技能継承",
    canProvide: "工場見学、製造案件の相談対応",
    hobbies: "釣り, 野球観戦", recentInterest: "IoT導入", motto: "現場に答えがある",
    urlWebsite: "https://example.com/inoue-factory",
    selfIntroduction: "ものづくりの現場から地域経済を見ています。",
    publicConsent: "同意する", ruleConsent: "同意する",
    tags: ["製造業", "DX推進", "経営者・代表"], isPublic: true, isDeleted: false,
    attendance: ["meet-2026-02", "meet-2026-03", "meet-2026-04", "meet-2026-01"],
    updatedAt: "2026-04-09 10:02", hue: 4,
  },
  {
    id: "m6", responseId: "resp-006", email: "misaki@example.com", submittedAt: "2026-04-01 07:15",
    fullName: "川島 美咲", nickname: "ミサキ", location: "兵庫県神戸市", birthDate: "1993-12-05",
    hometown: "兵庫県宝塚市", occupation: "フリーランスライター", ubmZone: "0→1", ubmMembershipType: "非会員",
    ubmJoinDate: "2025年12月",
    businessOverview: "ビジネス系オウンドメディアの編集と取材記事の執筆が中心。経営者インタビューを得意としています。",
    skills: "編集 / 取材 / 構成設計",
    canProvide: "記事企画、インタビュー代行",
    challenges: "継続案件の確保",
    hobbies: "読書, 映画", recentInterest: "地方取材", motto: "書く前に聴く",
    urlX: "https://x.com/example_misaki", urlNote: "https://note.com/example_misaki",
    urlWebsite: "https://example.com/kawashima",
    selfIntroduction: "人の物語を残す仕事をしています。",
    publicConsent: "同意する", ruleConsent: "同意する",
    tags: ["ライター・編集", "コンテンツ制作"], isPublic: true, isDeleted: false,
    attendance: ["meet-2026-04"], updatedAt: "2026-04-05 12:12", hue: 5,
  },
  {
    id: "m7", responseId: "resp-007", email: "yuta@example.com", submittedAt: "2026-03-25 22:50",
    fullName: "藤田 悠太", nickname: "ユウタ", location: "兵庫県神戸市", birthDate: "1992-07-07",
    hometown: "徳島県徳島市", occupation: "Webエンジニア", ubmZone: "1→10", ubmMembershipType: "会員",
    ubmJoinDate: "2024年5月",
    businessOverview: "受託開発と自社SaaSの二本立てで運営。Next.js と Cloudflare Workers が主戦場。",
    skills: "TypeScript / React / Cloudflare Workers",
    canProvide: "技術レビュー、アーキテクチャ相談",
    challenges: "営業の仕組み化",
    hobbies: "自作キーボード, ボルダリング", recentInterest: "エッジ AI", motto: "動くものが最強",
    urlWebsite: "https://example.com/fujita", urlX: "https://x.com/example_fujita",
    urlLinkedin: "https://linkedin.com/in/example-fujita",
    selfIntroduction: "作りたい人と作れる人をつなげたいです。",
    publicConsent: "同意する", ruleConsent: "同意する",
    tags: ["エンジニア", "Web・IT", "AI・データ"], isPublic: true, isDeleted: false,
    attendance: ["meet-2026-03", "meet-2026-04"], updatedAt: "2026-04-08 22:30", hue: 6,
  },
  {
    id: "m8", responseId: "resp-008", email: "riko@example.com", submittedAt: "2026-03-28 14:00",
    fullName: "小林 璃子", nickname: "リコ", location: "兵庫県西宮市", birthDate: "1988-04-22",
    hometown: "神奈川県横浜市", occupation: "コーチング・人材育成", ubmZone: "1→10", ubmMembershipType: "会員",
    ubmJoinDate: "2023年11月",
    businessOverview: "中小企業の管理職育成を中心にコーチング・研修を提供。対話型の人材開発が専門。",
    skills: "コーチング / 研修設計 / 1on1",
    canProvide: "管理職向け1on1研修、組織開発の相談",
    challenges: "法人営業の開拓",
    hobbies: "ピアノ, 散歩", recentInterest: "組織心理学", motto: "聴くは力なり",
    urlWebsite: "https://example.com/kobayashi", urlLinkedin: "https://linkedin.com/in/example-riko",
    urlInstagram: "https://instagram.com/example.riko",
    selfIntroduction: "安心して話せる場を、人にも組織にも作っていきたいです。",
    publicConsent: "同意する", ruleConsent: "同意する",
    tags: ["教育・コーチング", "人事・採用"], isPublic: true, isDeleted: false,
    attendance: ["meet-2026-01", "meet-2026-02", "meet-2026-04"],
    updatedAt: "2026-04-06 09:00", hue: 7,
  },
  {
    id: "m9", responseId: "resp-009", email: "daichi@example.com", submittedAt: "2026-03-26 10:33",
    fullName: "渡辺 大地", nickname: "ダイチ", location: "兵庫県加古川市", birthDate: "1983-10-14",
    hometown: "広島県広島市", occupation: "地域金融機関 事業支援担当", ubmZone: "10→100", ubmMembershipType: "会員",
    ubmJoinDate: "2023年6月",
    businessOverview: "地域金融機関で法人融資と事業再生を担当。創業期から事業承継まで幅広く伴走。",
    skills: "事業再生 / 補助金 / 資金調達",
    canProvide: "資金繰り相談、補助金申請のアドバイス",
    challenges: "若手経営者とのネットワーク拡大",
    hobbies: "トレイルラン, 史跡巡り", recentInterest: "地域商社", motto: "数字より先に現場",
    urlLinkedin: "https://linkedin.com/in/example-daichi",
    selfIntroduction: "お金の話を、経営者の言葉で翻訳する人でありたいです。",
    publicConsent: "同意する", ruleConsent: "同意する",
    tags: ["金融・保険", "経営戦略", "財務・会計"], isPublic: true, isDeleted: false,
    attendance: ["meet-2026-02", "meet-2026-03"], updatedAt: "2026-04-03 14:12", hue: 2,
  },
  {
    id: "m10", responseId: "resp-010", email: "nao@example.com", submittedAt: "2026-04-02 16:50",
    fullName: "坂本 奈央", nickname: "なお", location: "兵庫県三田市", birthDate: "1995-01-28",
    hometown: "兵庫県三田市", occupation: "動画クリエイター", ubmZone: "0→1", ubmMembershipType: "アカデミー生",
    ubmJoinDate: "2025年9月",
    businessOverview: "中小事業者向けにショート動画とYouTube運用を提供。撮影から編集・運用まで一人で完結。",
    skills: "映像編集 / SNS運用 / 企画",
    canProvide: "動画企画、ショート動画の制作",
    challenges: "単価交渉と案件の標準化",
    hobbies: "カフェ巡り, 写真", recentInterest: "縦型動画の構成", motto: "尺より密度",
    urlInstagram: "https://instagram.com/example.nao", urlYoutube: "https://youtube.com/@example_nao",
    urlTiktok: "https://tiktok.com/@example_nao",
    selfIntroduction: "小さな事業の魅力を動画で引き出したいです。",
    publicConsent: "同意する", ruleConsent: "同意する",
    tags: ["動画・映像", "SNS運用", "コンテンツ制作"], isPublic: true, isDeleted: false,
    attendance: ["meet-2026-04"], updatedAt: "2026-04-06 20:15", hue: 3,
  },
  {
    id: "m11", responseId: "resp-011", email: "ryo@example.com", submittedAt: "2026-03-20 12:00",
    fullName: "長谷川 遼", nickname: "リョウ", location: "兵庫県神戸市", birthDate: "1975-08-08",
    hometown: "兵庫県神戸市", occupation: "不動産仲介・管理", ubmZone: "10→100", ubmMembershipType: "会員",
    ubmJoinDate: "2022年4月",
    businessOverview: "神戸市内を中心に中小事業者向けの物件仲介と管理。創業支援や店舗立ち上げもサポート。",
    skills: "店舗物件 / テナント仲介 / 管理運営",
    canProvide: "物件相談、創業時の立地アドバイス",
    challenges: "次世代への事業承継",
    hobbies: "ゴルフ, 食べ歩き", recentInterest: "空き家活用", motto: "縁はご縁",
    urlWebsite: "https://example.com/hasegawa",
    selfIntroduction: "地域に根ざした不動産の仕事をしています。",
    publicConsent: "同意する", ruleConsent: "同意する",
    tags: ["不動産", "営業・販売"], isPublic: true, isDeleted: false,
    attendance: ["meet-2026-01", "meet-2026-02", "meet-2026-03"],
    updatedAt: "2026-04-02 15:30", hue: 4,
  },
  {
    id: "m12", responseId: "resp-012", email: "yui@example.com", submittedAt: "2026-04-03 09:45",
    fullName: "森 結衣", nickname: "ゆい", location: "兵庫県豊岡市", birthDate: "1991-05-11",
    hometown: "兵庫県豊岡市", occupation: "ゲストハウス運営", ubmZone: "1→10", ubmMembershipType: "会員",
    ubmJoinDate: "2024年8月",
    businessOverview: "但馬地域でゲストハウスと地域体験プログラムを運営。インバウンド誘客と地域内経済循環の接続。",
    skills: "観光企画 / SNSマーケ / 多言語接客",
    canProvide: "地域体験プログラムの設計、合宿誘致",
    challenges: "オフシーズンの稼働率",
    hobbies: "登山, 発酵食", recentInterest: "地域通貨", motto: "泊まるは関わる入り口",
    urlInstagram: "https://instagram.com/example.yui", urlWebsite: "https://example.com/mori-guesthouse",
    selfIntroduction: "旅から始まる関係人口作りを目指しています。",
    publicConsent: "同意する", ruleConsent: "同意する",
    tags: ["旅行・観光", "マーケティング", "事業開発"], isPublic: true, isDeleted: false,
    attendance: ["meet-2026-03"], updatedAt: "2026-04-06 16:12", hue: 5,
  },
  {
    id: "m13", responseId: "resp-013", email: "former@example.com", submittedAt: "2025-11-10 08:00",
    fullName: "高橋 拓也", nickname: "タクヤ", location: "兵庫県加西市", birthDate: "1986-02-03",
    hometown: "兵庫県加西市", occupation: "（退会）", ubmZone: "1→10", ubmMembershipType: "非会員",
    ubmJoinDate: "2023年3月",
    businessOverview: "事業形態の変更に伴い退会。",
    publicConsent: "同意する", ruleConsent: "同意する",
    tags: [], isPublic: false, isDeleted: true,
    attendance: ["meet-2025-12"], updatedAt: "2025-11-20 10:15", hue: 0,
    deletedAt: "2025-11-20", deletedReason: "本人希望",
  },
];

const SCHEMA_DIFF = [
  { type: "added", stableKey: null, questionId: "q_2026apr_01", itemId: "i_891", label: "会社紹介文", note: "2026-04-08 のフォーム編集で追加" },
  { type: "changed", stableKey: "businessOverview", questionId: "q_1f3d21", label: "ビジネス概要", note: "プレースホルダー文言が更新 (位置は変わらず)" },
  { type: "changed", stableKey: "urlX", questionId: "q_x901", label: "X（Twitter）URL", note: "「Twitter」→「X」に表記変更" },
  { type: "removed", stableKey: "urlThreads", questionId: "q_8ea1", label: "Threads URL", note: "旧回答は保持。UIからは非表示扱いに" },
  { type: "unresolved", stableKey: null, questionId: "q_unmapped_7711", label: "名刺配布OK？", note: "新規追加 — stableKey 未割当" },
];

const SCHEMA_VERSIONS = [
  { revisionId: "rev-20260408-1", schemaHash: "a3f9b2d1", date: "2026-04-08 16:20", state: "active", fieldCount: 31, unknownCount: 1 },
  { revisionId: "rev-20260312-1", schemaHash: "7e21c8a4", date: "2026-03-12 10:05", state: "superseded", fieldCount: 30, unknownCount: 0 },
  { revisionId: "rev-20260215-1", schemaHash: "c991f2d8", date: "2026-02-15 09:30", state: "superseded", fieldCount: 30, unknownCount: 0 },
];

const ALIAS_HISTORY = [
  { stableKey: "urlX", oldQuestionId: "q_twitter_771", newQuestionId: "q_x901", resolvedAt: "2026-04-08 16:22", resolvedBy: "admin@example.com" },
  { stableKey: "businessOverview", oldQuestionId: "q_1f3c", newQuestionId: "q_1f3d21", resolvedAt: "2026-03-12 10:08", resolvedBy: "system" },
];

window.UBM = {
  SURVEY_SECTIONS, TAG_CATALOG, ALL_TAGS, MEETINGS, MEMBERS,
  SCHEMA_DIFF, SCHEMA_VERSIONS, ALIAS_HISTORY,
};
