INSERT OR REPLACE INTO schema_versions (revision_id, form_id, schema_hash, state, synced_at, field_count, unknown_field_count, source_url) VALUES
  ('TEST-REV-DUP', 'TEST-FORM-DUP', 'TEST-SCHEMA-HASH-DUP', 'active', '2026-06-09T10:00:00.000Z', 6, 0, 'seed:identity-conflicts');

INSERT OR REPLACE INTO schema_questions (question_pk, revision_id, stable_key, question_id, item_id, section_key, section_title, label, kind, position, required, visibility, searchable, status, choice_labels_json) VALUES
  ('TEST-REV-DUP:fullName', 'TEST-REV-DUP', 'fullName', 'TEST-DUP-Q-01', 'TEST-DUP-ITEM-01', 'basic_profile', '基本プロフィール', 'お名前（フルネーム）', 'shortText', 1, 1, 'public', 1, 'active', '[]'),
  ('TEST-REV-DUP:occupation', 'TEST-REV-DUP', 'occupation', 'TEST-DUP-Q-02', 'TEST-DUP-ITEM-02', 'basic_profile', '基本プロフィール', '職業・仕事内容', 'shortText', 2, 1, 'public', 1, 'active', '[]'),
  ('TEST-REV-DUP:ubmZone', 'TEST-REV-DUP', 'ubmZone', 'TEST-DUP-Q-03', 'TEST-DUP-ITEM-03', 'basic_profile', '基本プロフィール', 'UBM区画', 'shortText', 3, 0, 'public', 1, 'active', '[]'),
  ('TEST-REV-DUP:location', 'TEST-REV-DUP', 'location', 'TEST-DUP-Q-04', 'TEST-DUP-ITEM-04', 'message', 'メッセージ', 'お住まい', 'shortText', 4, 0, 'public', 1, 'active', '[]'),
  ('TEST-REV-DUP:businessOverview', 'TEST-REV-DUP', 'businessOverview', 'TEST-DUP-Q-05', 'TEST-DUP-ITEM-05', 'message', 'メッセージ', 'ビジネス概要', 'paragraph', 5, 0, 'public', 1, 'active', '[]'),
  ('TEST-REV-DUP:selfIntroduction', 'TEST-REV-DUP', 'selfIntroduction', 'TEST-DUP-Q-06', 'TEST-DUP-ITEM-06', 'message', 'メッセージ', '自己紹介・一言メッセージ', 'paragraph', 6, 0, 'public', 1, 'active', '[]');

INSERT OR REPLACE INTO member_responses (response_id, form_id, revision_id, schema_hash, response_email, submitted_at, edit_response_url, answers_json, raw_answers_json, extra_fields_json, unmapped_question_ids_json, search_text) VALUES
  ('TEST-RES-21', 'TEST-FORM-DUP', 'TEST-REV-DUP', 'TEST-SCHEMA-HASH-DUP', 'test-dup-21@test.ubm-hyogo.invalid', '2026-06-09T10:00:00.000Z', 'https://forms.test.invalid/edit/TEST-RES-21', '{"fullName":"[TEST] 重複 完全一致 太郎","occupation":"行政書士","ubmZone":"0_to_1","location":"兵庫県神戸市","businessOverview":"完全一致パターンの古い登録です。","selfIntroduction":"重複候補の動作確認用データです。"}', '{"fullName":"[TEST] 重複 完全一致 太郎","occupation":"行政書士","ubmZone":"0_to_1","location":"兵庫県神戸市","businessOverview":"完全一致パターンの古い登録です。","selfIntroduction":"重複候補の動作確認用データです。"}', '{"source":"seed:identity-conflicts"}', '[]', '[TEST] 重複 完全一致 太郎 行政書士 0_to_1 test-dup-21@test.ubm-hyogo.invalid 兵庫県神戸市'),
  ('TEST-RES-22', 'TEST-FORM-DUP', 'TEST-REV-DUP', 'TEST-SCHEMA-HASH-DUP', 'test-dup-22@test.ubm-hyogo.invalid', '2026-06-09T10:01:00.000Z', 'https://forms.test.invalid/edit/TEST-RES-22', '{"fullName":"[TEST] 重複 完全一致 太郎","occupation":"行政書士","ubmZone":"0_to_1","location":"兵庫県神戸市","businessOverview":"完全一致パターンの新しい登録です。","selfIntroduction":"統合操作の確認に使います。"}', '{"fullName":"[TEST] 重複 完全一致 太郎","occupation":"行政書士","ubmZone":"0_to_1","location":"兵庫県神戸市","businessOverview":"完全一致パターンの新しい登録です。","selfIntroduction":"統合操作の確認に使います。"}', '{"source":"seed:identity-conflicts"}', '[]', '[TEST] 重複 完全一致 太郎 行政書士 0_to_1 test-dup-22@test.ubm-hyogo.invalid 兵庫県神戸市'),
  ('TEST-RES-23', 'TEST-FORM-DUP', 'TEST-REV-DUP', 'TEST-SCHEMA-HASH-DUP', 'test-dup-23@test.ubm-hyogo.invalid', '2026-06-09T10:02:00.000Z', 'https://forms.test.invalid/edit/TEST-RES-23', '{"fullName":"[TEST] 重複 表記ゆれ 花子","occupation":"ＷＥＢデザイナー","ubmZone":"1_to_10","location":"兵庫県西宮市","businessOverview":"全角WEB表記の登録です。","selfIntroduction":"NFKC 正規化の確認に使います。"}', '{"fullName":"[TEST] 重複 表記ゆれ 花子","occupation":"ＷＥＢデザイナー","ubmZone":"1_to_10","location":"兵庫県西宮市","businessOverview":"全角WEB表記の登録です。","selfIntroduction":"NFKC 正規化の確認に使います。"}', '{"source":"seed:identity-conflicts"}', '[]', '[TEST] 重複 表記ゆれ 花子 ＷＥＢデザイナー 1_to_10 test-dup-23@test.ubm-hyogo.invalid 兵庫県西宮市'),
  ('TEST-RES-24', 'TEST-FORM-DUP', 'TEST-REV-DUP', 'TEST-SCHEMA-HASH-DUP', 'test-dup-24@test.ubm-hyogo.invalid', '2026-06-09T10:03:00.000Z', 'https://forms.test.invalid/edit/TEST-RES-24', '{"fullName":"[TEST] 重複 表記ゆれ 花子","occupation":"WEBデザイナー","ubmZone":"1_to_10","location":"兵庫県西宮市","businessOverview":"半角WEB表記の登録です。","selfIntroduction":"NFKC 正規化の確認に使います。"}', '{"fullName":"[TEST] 重複 表記ゆれ 花子","occupation":"WEBデザイナー","ubmZone":"1_to_10","location":"兵庫県西宮市","businessOverview":"半角WEB表記の登録です。","selfIntroduction":"NFKC 正規化の確認に使います。"}', '{"source":"seed:identity-conflicts"}', '[]', '[TEST] 重複 表記ゆれ 花子 WEBデザイナー 1_to_10 test-dup-24@test.ubm-hyogo.invalid 兵庫県西宮市'),
  ('TEST-RES-25', 'TEST-FORM-DUP', 'TEST-REV-DUP', 'TEST-SCHEMA-HASH-DUP', 'test-dup-25@test.ubm-hyogo.invalid', '2026-06-09T10:04:00.000Z', 'https://forms.test.invalid/edit/TEST-RES-25', '{"fullName":"[TEST] 重複 余白 次郎","occupation":"製造コンサルタント","ubmZone":"10_to_100","location":"兵庫県姫路市","businessOverview":"余白なしの登録です。","selfIntroduction":"trim 正規化の確認に使います。"}', '{"fullName":"[TEST] 重複 余白 次郎","occupation":"製造コンサルタント","ubmZone":"10_to_100","location":"兵庫県姫路市","businessOverview":"余白なしの登録です。","selfIntroduction":"trim 正規化の確認に使います。"}', '{"source":"seed:identity-conflicts"}', '[]', '[TEST] 重複 余白 次郎 製造コンサルタント 10_to_100 test-dup-25@test.ubm-hyogo.invalid 兵庫県姫路市'),
  ('TEST-RES-26', 'TEST-FORM-DUP', 'TEST-REV-DUP', 'TEST-SCHEMA-HASH-DUP', 'test-dup-26@test.ubm-hyogo.invalid', '2026-06-09T10:05:00.000Z', 'https://forms.test.invalid/edit/TEST-RES-26', '{"fullName":"[TEST] 重複 余白 次郎 ","occupation":"製造コンサルタント ","ubmZone":"10_to_100","location":"兵庫県姫路市","businessOverview":"末尾空白を含む登録です。","selfIntroduction":"trim 正規化の確認に使います。"}', '{"fullName":"[TEST] 重複 余白 次郎 ","occupation":"製造コンサルタント ","ubmZone":"10_to_100","location":"兵庫県姫路市","businessOverview":"末尾空白を含む登録です。","selfIntroduction":"trim 正規化の確認に使います。"}', '{"source":"seed:identity-conflicts"}', '[]', '[TEST] 重複 余白 次郎  製造コンサルタント  10_to_100 test-dup-26@test.ubm-hyogo.invalid 兵庫県姫路市'),
  ('TEST-RES-27', 'TEST-FORM-DUP', 'TEST-REV-DUP', 'TEST-SCHEMA-HASH-DUP', 'test-dup-27@test.ubm-hyogo.invalid', '2026-06-09T10:06:00.000Z', 'https://forms.test.invalid/edit/TEST-RES-27', '{"fullName":"[TEST] 重複 転居 三郎","occupation":"不動産業","ubmZone":"0_to_1","location":"兵庫県明石市","businessOverview":"転居前の登録です。","selfIntroduction":"ゾーン違いでも候補化されることを確認します。"}', '{"fullName":"[TEST] 重複 転居 三郎","occupation":"不動産業","ubmZone":"0_to_1","location":"兵庫県明石市","businessOverview":"転居前の登録です。","selfIntroduction":"ゾーン違いでも候補化されることを確認します。"}', '{"source":"seed:identity-conflicts"}', '[]', '[TEST] 重複 転居 三郎 不動産業 0_to_1 test-dup-27@test.ubm-hyogo.invalid 兵庫県明石市'),
  ('TEST-RES-28', 'TEST-FORM-DUP', 'TEST-REV-DUP', 'TEST-SCHEMA-HASH-DUP', 'test-dup-28@test.ubm-hyogo.invalid', '2026-06-09T10:07:00.000Z', 'https://forms.test.invalid/edit/TEST-RES-28', '{"fullName":"[TEST] 重複 転居 三郎","occupation":"不動産業","ubmZone":"1_to_10","location":"兵庫県加古川市","businessOverview":"転居後の登録です。","selfIntroduction":"ゾーン違いでも候補化されることを確認します。"}', '{"fullName":"[TEST] 重複 転居 三郎","occupation":"不動産業","ubmZone":"1_to_10","location":"兵庫県加古川市","businessOverview":"転居後の登録です。","selfIntroduction":"ゾーン違いでも候補化されることを確認します。"}', '{"source":"seed:identity-conflicts"}', '[]', '[TEST] 重複 転居 三郎 不動産業 1_to_10 test-dup-28@test.ubm-hyogo.invalid 兵庫県加古川市'),
  ('TEST-RES-29', 'TEST-FORM-DUP', 'TEST-REV-DUP', 'TEST-SCHEMA-HASH-DUP', 'test-dup-29@test.ubm-hyogo.invalid', '2026-06-09T10:08:00.000Z', 'https://forms.test.invalid/edit/TEST-RES-29', '{"fullName":"[TEST] 重複 同姓同名 美咲","occupation":"美容師","ubmZone":"1_to_10","location":"兵庫県尼崎市","businessOverview":"同姓同名の別人想定です。","selfIntroduction":"別人として確定の確認に使います。"}', '{"fullName":"[TEST] 重複 同姓同名 美咲","occupation":"美容師","ubmZone":"1_to_10","location":"兵庫県尼崎市","businessOverview":"同姓同名の別人想定です。","selfIntroduction":"別人として確定の確認に使います。"}', '{"source":"seed:identity-conflicts"}', '[]', '[TEST] 重複 同姓同名 美咲 美容師 1_to_10 test-dup-29@test.ubm-hyogo.invalid 兵庫県尼崎市'),
  ('TEST-RES-30', 'TEST-FORM-DUP', 'TEST-REV-DUP', 'TEST-SCHEMA-HASH-DUP', 'test-dup-30@test.ubm-hyogo.invalid', '2026-06-09T10:09:00.000Z', 'https://forms.test.invalid/edit/TEST-RES-30', '{"fullName":"[TEST] 重複 同姓同名 美咲","occupation":"美容師","ubmZone":"10_to_100","location":"兵庫県宝塚市","businessOverview":"同姓同名の別人想定です。","selfIntroduction":"別人として確定の確認に使います。"}', '{"fullName":"[TEST] 重複 同姓同名 美咲","occupation":"美容師","ubmZone":"10_to_100","location":"兵庫県宝塚市","businessOverview":"同姓同名の別人想定です。","selfIntroduction":"別人として確定の確認に使います。"}', '{"source":"seed:identity-conflicts"}', '[]', '[TEST] 重複 同姓同名 美咲 美容師 10_to_100 test-dup-30@test.ubm-hyogo.invalid 兵庫県宝塚市');

INSERT OR REPLACE INTO response_fields (response_id, stable_key, value_json, raw_value_json) VALUES
  ('TEST-RES-21', 'fullName', '"[TEST] 重複 完全一致 太郎"', '"[TEST] 重複 完全一致 太郎"'),
  ('TEST-RES-21', 'occupation', '"行政書士"', '"行政書士"'),
  ('TEST-RES-21', 'ubmZone', '"0_to_1"', '"0_to_1"'),
  ('TEST-RES-21', 'location', '"兵庫県神戸市"', '"兵庫県神戸市"'),
  ('TEST-RES-21', 'businessOverview', '"完全一致パターンの古い登録です。"', '"完全一致パターンの古い登録です。"'),
  ('TEST-RES-21', 'selfIntroduction', '"重複候補の動作確認用データです。"', '"重複候補の動作確認用データです。"'),
  ('TEST-RES-22', 'fullName', '"[TEST] 重複 完全一致 太郎"', '"[TEST] 重複 完全一致 太郎"'),
  ('TEST-RES-22', 'occupation', '"行政書士"', '"行政書士"'),
  ('TEST-RES-22', 'ubmZone', '"0_to_1"', '"0_to_1"'),
  ('TEST-RES-22', 'location', '"兵庫県神戸市"', '"兵庫県神戸市"'),
  ('TEST-RES-22', 'businessOverview', '"完全一致パターンの新しい登録です。"', '"完全一致パターンの新しい登録です。"'),
  ('TEST-RES-22', 'selfIntroduction', '"統合操作の確認に使います。"', '"統合操作の確認に使います。"'),
  ('TEST-RES-23', 'fullName', '"[TEST] 重複 表記ゆれ 花子"', '"[TEST] 重複 表記ゆれ 花子"'),
  ('TEST-RES-23', 'occupation', '"ＷＥＢデザイナー"', '"ＷＥＢデザイナー"'),
  ('TEST-RES-23', 'ubmZone', '"1_to_10"', '"1_to_10"'),
  ('TEST-RES-23', 'location', '"兵庫県西宮市"', '"兵庫県西宮市"'),
  ('TEST-RES-23', 'businessOverview', '"全角WEB表記の登録です。"', '"全角WEB表記の登録です。"'),
  ('TEST-RES-23', 'selfIntroduction', '"NFKC 正規化の確認に使います。"', '"NFKC 正規化の確認に使います。"'),
  ('TEST-RES-24', 'fullName', '"[TEST] 重複 表記ゆれ 花子"', '"[TEST] 重複 表記ゆれ 花子"'),
  ('TEST-RES-24', 'occupation', '"WEBデザイナー"', '"WEBデザイナー"'),
  ('TEST-RES-24', 'ubmZone', '"1_to_10"', '"1_to_10"'),
  ('TEST-RES-24', 'location', '"兵庫県西宮市"', '"兵庫県西宮市"'),
  ('TEST-RES-24', 'businessOverview', '"半角WEB表記の登録です。"', '"半角WEB表記の登録です。"'),
  ('TEST-RES-24', 'selfIntroduction', '"NFKC 正規化の確認に使います。"', '"NFKC 正規化の確認に使います。"'),
  ('TEST-RES-25', 'fullName', '"[TEST] 重複 余白 次郎"', '"[TEST] 重複 余白 次郎"'),
  ('TEST-RES-25', 'occupation', '"製造コンサルタント"', '"製造コンサルタント"'),
  ('TEST-RES-25', 'ubmZone', '"10_to_100"', '"10_to_100"'),
  ('TEST-RES-25', 'location', '"兵庫県姫路市"', '"兵庫県姫路市"'),
  ('TEST-RES-25', 'businessOverview', '"余白なしの登録です。"', '"余白なしの登録です。"'),
  ('TEST-RES-25', 'selfIntroduction', '"trim 正規化の確認に使います。"', '"trim 正規化の確認に使います。"'),
  ('TEST-RES-26', 'fullName', '"[TEST] 重複 余白 次郎 "', '"[TEST] 重複 余白 次郎 "'),
  ('TEST-RES-26', 'occupation', '"製造コンサルタント "', '"製造コンサルタント "'),
  ('TEST-RES-26', 'ubmZone', '"10_to_100"', '"10_to_100"'),
  ('TEST-RES-26', 'location', '"兵庫県姫路市"', '"兵庫県姫路市"'),
  ('TEST-RES-26', 'businessOverview', '"末尾空白を含む登録です。"', '"末尾空白を含む登録です。"'),
  ('TEST-RES-26', 'selfIntroduction', '"trim 正規化の確認に使います。"', '"trim 正規化の確認に使います。"'),
  ('TEST-RES-27', 'fullName', '"[TEST] 重複 転居 三郎"', '"[TEST] 重複 転居 三郎"'),
  ('TEST-RES-27', 'occupation', '"不動産業"', '"不動産業"'),
  ('TEST-RES-27', 'ubmZone', '"0_to_1"', '"0_to_1"'),
  ('TEST-RES-27', 'location', '"兵庫県明石市"', '"兵庫県明石市"'),
  ('TEST-RES-27', 'businessOverview', '"転居前の登録です。"', '"転居前の登録です。"'),
  ('TEST-RES-27', 'selfIntroduction', '"ゾーン違いでも候補化されることを確認します。"', '"ゾーン違いでも候補化されることを確認します。"'),
  ('TEST-RES-28', 'fullName', '"[TEST] 重複 転居 三郎"', '"[TEST] 重複 転居 三郎"'),
  ('TEST-RES-28', 'occupation', '"不動産業"', '"不動産業"'),
  ('TEST-RES-28', 'ubmZone', '"1_to_10"', '"1_to_10"'),
  ('TEST-RES-28', 'location', '"兵庫県加古川市"', '"兵庫県加古川市"'),
  ('TEST-RES-28', 'businessOverview', '"転居後の登録です。"', '"転居後の登録です。"'),
  ('TEST-RES-28', 'selfIntroduction', '"ゾーン違いでも候補化されることを確認します。"', '"ゾーン違いでも候補化されることを確認します。"'),
  ('TEST-RES-29', 'fullName', '"[TEST] 重複 同姓同名 美咲"', '"[TEST] 重複 同姓同名 美咲"'),
  ('TEST-RES-29', 'occupation', '"美容師"', '"美容師"'),
  ('TEST-RES-29', 'ubmZone', '"1_to_10"', '"1_to_10"'),
  ('TEST-RES-29', 'location', '"兵庫県尼崎市"', '"兵庫県尼崎市"'),
  ('TEST-RES-29', 'businessOverview', '"同姓同名の別人想定です。"', '"同姓同名の別人想定です。"'),
  ('TEST-RES-29', 'selfIntroduction', '"別人として確定の確認に使います。"', '"別人として確定の確認に使います。"'),
  ('TEST-RES-30', 'fullName', '"[TEST] 重複 同姓同名 美咲"', '"[TEST] 重複 同姓同名 美咲"'),
  ('TEST-RES-30', 'occupation', '"美容師"', '"美容師"'),
  ('TEST-RES-30', 'ubmZone', '"10_to_100"', '"10_to_100"'),
  ('TEST-RES-30', 'location', '"兵庫県宝塚市"', '"兵庫県宝塚市"'),
  ('TEST-RES-30', 'businessOverview', '"同姓同名の別人想定です。"', '"同姓同名の別人想定です。"'),
  ('TEST-RES-30', 'selfIntroduction', '"別人として確定の確認に使います。"', '"別人として確定の確認に使います。"');

INSERT OR REPLACE INTO member_identities (member_id, response_email, current_response_id, first_response_id, last_submitted_at, created_at, updated_at) VALUES
  ('TEST-MEM-21', 'test-dup-21@test.ubm-hyogo.invalid', 'TEST-RES-21', 'TEST-RES-21', '2026-06-09T10:00:00.000Z', '2026-06-09T10:00:00.000Z', '2026-06-09T10:00:00.000Z'),
  ('TEST-MEM-22', 'test-dup-22@test.ubm-hyogo.invalid', 'TEST-RES-22', 'TEST-RES-22', '2026-06-09T10:01:00.000Z', '2026-06-09T10:01:00.000Z', '2026-06-09T10:01:00.000Z'),
  ('TEST-MEM-23', 'test-dup-23@test.ubm-hyogo.invalid', 'TEST-RES-23', 'TEST-RES-23', '2026-06-09T10:02:00.000Z', '2026-06-09T10:02:00.000Z', '2026-06-09T10:02:00.000Z'),
  ('TEST-MEM-24', 'test-dup-24@test.ubm-hyogo.invalid', 'TEST-RES-24', 'TEST-RES-24', '2026-06-09T10:03:00.000Z', '2026-06-09T10:03:00.000Z', '2026-06-09T10:03:00.000Z'),
  ('TEST-MEM-25', 'test-dup-25@test.ubm-hyogo.invalid', 'TEST-RES-25', 'TEST-RES-25', '2026-06-09T10:04:00.000Z', '2026-06-09T10:04:00.000Z', '2026-06-09T10:04:00.000Z'),
  ('TEST-MEM-26', 'test-dup-26@test.ubm-hyogo.invalid', 'TEST-RES-26', 'TEST-RES-26', '2026-06-09T10:05:00.000Z', '2026-06-09T10:05:00.000Z', '2026-06-09T10:05:00.000Z'),
  ('TEST-MEM-27', 'test-dup-27@test.ubm-hyogo.invalid', 'TEST-RES-27', 'TEST-RES-27', '2026-06-09T10:06:00.000Z', '2026-06-09T10:06:00.000Z', '2026-06-09T10:06:00.000Z'),
  ('TEST-MEM-28', 'test-dup-28@test.ubm-hyogo.invalid', 'TEST-RES-28', 'TEST-RES-28', '2026-06-09T10:07:00.000Z', '2026-06-09T10:07:00.000Z', '2026-06-09T10:07:00.000Z'),
  ('TEST-MEM-29', 'test-dup-29@test.ubm-hyogo.invalid', 'TEST-RES-29', 'TEST-RES-29', '2026-06-09T10:08:00.000Z', '2026-06-09T10:08:00.000Z', '2026-06-09T10:08:00.000Z'),
  ('TEST-MEM-30', 'test-dup-30@test.ubm-hyogo.invalid', 'TEST-RES-30', 'TEST-RES-30', '2026-06-09T10:09:00.000Z', '2026-06-09T10:09:00.000Z', '2026-06-09T10:09:00.000Z');

INSERT OR REPLACE INTO member_status (member_id, public_consent, rules_consent, publish_state, is_deleted, hidden_reason, updated_by, updated_at, notification_opt_out) VALUES
  ('TEST-MEM-21', 'declined', 'consented', 'member_only', 0, NULL, 'seed:identity-conflicts', '2026-06-09T10:00:00.000Z', 0),
  ('TEST-MEM-22', 'declined', 'consented', 'member_only', 0, NULL, 'seed:identity-conflicts', '2026-06-09T10:01:00.000Z', 0),
  ('TEST-MEM-23', 'declined', 'consented', 'member_only', 0, NULL, 'seed:identity-conflicts', '2026-06-09T10:02:00.000Z', 0),
  ('TEST-MEM-24', 'declined', 'consented', 'member_only', 0, NULL, 'seed:identity-conflicts', '2026-06-09T10:03:00.000Z', 0),
  ('TEST-MEM-25', 'declined', 'consented', 'member_only', 0, NULL, 'seed:identity-conflicts', '2026-06-09T10:04:00.000Z', 0),
  ('TEST-MEM-26', 'declined', 'consented', 'member_only', 0, NULL, 'seed:identity-conflicts', '2026-06-09T10:05:00.000Z', 0),
  ('TEST-MEM-27', 'declined', 'consented', 'member_only', 0, NULL, 'seed:identity-conflicts', '2026-06-09T10:06:00.000Z', 0),
  ('TEST-MEM-28', 'declined', 'consented', 'member_only', 0, NULL, 'seed:identity-conflicts', '2026-06-09T10:07:00.000Z', 0),
  ('TEST-MEM-29', 'declined', 'consented', 'member_only', 0, NULL, 'seed:identity-conflicts', '2026-06-09T10:08:00.000Z', 0),
  ('TEST-MEM-30', 'declined', 'consented', 'member_only', 0, NULL, 'seed:identity-conflicts', '2026-06-09T10:09:00.000Z', 0);
