DELETE FROM member_status WHERE member_id IN ('TEST-MEM-21', 'TEST-MEM-22', 'TEST-MEM-23', 'TEST-MEM-24', 'TEST-MEM-25', 'TEST-MEM-26', 'TEST-MEM-27', 'TEST-MEM-28', 'TEST-MEM-29', 'TEST-MEM-30');
DELETE FROM member_identities WHERE member_id IN ('TEST-MEM-21', 'TEST-MEM-22', 'TEST-MEM-23', 'TEST-MEM-24', 'TEST-MEM-25', 'TEST-MEM-26', 'TEST-MEM-27', 'TEST-MEM-28', 'TEST-MEM-29', 'TEST-MEM-30');
DELETE FROM response_fields WHERE response_id IN ('TEST-RES-21', 'TEST-RES-22', 'TEST-RES-23', 'TEST-RES-24', 'TEST-RES-25', 'TEST-RES-26', 'TEST-RES-27', 'TEST-RES-28', 'TEST-RES-29', 'TEST-RES-30');
DELETE FROM member_responses WHERE response_id IN ('TEST-RES-21', 'TEST-RES-22', 'TEST-RES-23', 'TEST-RES-24', 'TEST-RES-25', 'TEST-RES-26', 'TEST-RES-27', 'TEST-RES-28', 'TEST-RES-29', 'TEST-RES-30');
DELETE FROM schema_questions WHERE revision_id = 'TEST-REV-DUP';
DELETE FROM schema_versions WHERE revision_id = 'TEST-REV-DUP';
