export type IconName =
  | "chevron-down"
  | "chevron-up"
  | "x"
  | "search"
  | "check"
  | "menu"
  | "external-link"
  | "send"
  | "inbox"
  | "arrow-left"
  | "briefcase"
  | "map-pin"
  | "chevron-right"
  | "help";
