#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat >&2 <<'USAGE'
Usage: scripts/ci/verify-workflow-doc-refs.sh [--root <repo-root>] [--workflows <dir>]

Checks docs/...md references in GitHub workflow YAML files and fails if a
referenced repository-local markdown file does not exist.
USAGE
}

repo_root="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
workflows_dir=".github/workflows"

while [ "$#" -gt 0 ]; do
  case "$1" in
    --root)
      [ "$#" -ge 2 ] || { usage; exit 2; }
      repo_root="$2"
      shift 2
      ;;
    --workflows)
      [ "$#" -ge 2 ] || { usage; exit 2; }
      workflows_dir="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "unknown arg: $1" >&2
      usage
      exit 2
      ;;
  esac
done

cd "$repo_root"

if [ ! -d "$workflows_dir" ]; then
  echo "workflows dir not found: $workflows_dir" >&2
  exit 2
fi

tmp_report="$(mktemp)"
trap 'rm -f "$tmp_report"' EXIT

checked=0
files=0

while IFS= read -r workflow; do
  files=$((files + 1))
  while IFS=: read -r line_no line; do
    while IFS= read -r match; do
      [ -n "$match" ] || continue
      case "$match" in
        http://*|https://*)
          # External URLs are not repository-local doc references.
          continue
          ;;
      esac
      ref="$(printf '%s\n' "$match" | grep -oE 'docs/[A-Za-z0-9_./#-]+\.md(#[A-Za-z0-9_.:/?=&%+~,-]+)?' | head -n 1 || true)"
      [ -n "$ref" ] || continue
      path="${ref%%#*}"
      case "$path" in
        */outputs/phase-11/evidence/*)
          # Runtime evidence files are generated by the workflow run itself.
          continue
          ;;
        *'...'*)
          # Human input placeholders are not repository paths.
          continue
          ;;
      esac
      checked=$((checked + 1))
      if [ ! -f "$path" ]; then
        printf '%s:%s -> %s\n' "$workflow" "$line_no" "$path" >> "$tmp_report"
      fi
    done < <(printf '%s\n' "$line" | grep -oE '(https?://[^[:space:]'\''")]*docs/[A-Za-z0-9_./#-]+\.md(#[A-Za-z0-9_.:/?=&%+~,-]+)?|docs/[A-Za-z0-9_./#-]+\.md(#[A-Za-z0-9_.:/?=&%+~,-]+)?)' || true)
  done < <(grep -nE 'docs/[A-Za-z0-9_./#-]+\.md' "$workflow" || true)
done < <(find "$workflows_dir" -maxdepth 1 -type f \( -name '*.yml' -o -name '*.yaml' \) | sort)

if [ -s "$tmp_report" ]; then
  printf 'verify-workflow-doc-refs: MISSING\n'
  cat "$tmp_report"
  exit 1
fi

printf 'verify-workflow-doc-refs: OK (%d references checked across %d files)\n' "$checked" "$files"
