#!/usr/bin/env bash
# scripts/coverage-gate-e2e.sh
#
# E2E line coverage 80% gate.
# - Reads json-summary generated by monocart-reporter (apps/web/coverage/coverage-summary.json)
# - Fails (exit 1) when total.lines.pct < 80
#
# coverage threshold = 80%
# source: .claude/skills/task-specification-creator/references/quality-gates.md §7.5
# tier: standard / metric: lines
#
# requires: jq, awk
# usage:
#   bash scripts/coverage-gate-e2e.sh
#
# fixture override (used by Phase 4 tests):
#   THRESHOLD_FIXTURE=scripts/__tests__/coverage-gate-e2e.fixture/pass \
#     bash scripts/coverage-gate-e2e.sh
#
# Outputs GitHub Actions-style annotations:
#   ::notice::line coverage <pct> >= 80
#   ::error::line coverage <pct> < 80

set -euo pipefail

THRESHOLD=80
SUMMARY="apps/web/coverage/coverage-summary.json"

# Fixture mode: override SUMMARY to a fixed path for unit tests.
if [[ -n "${THRESHOLD_FIXTURE:-}" ]]; then
  SUMMARY="${THRESHOLD_FIXTURE}/coverage-summary.json"
fi

if [[ ! -f "${SUMMARY}" ]]; then
  echo "::error::coverage-summary.json not found at ${SUMMARY}"
  exit 1
fi

PCT="$(jq -r '.total.lines.pct' "${SUMMARY}")"

if [[ -z "${PCT}" || "${PCT}" == "null" ]]; then
  echo "::error::failed to read total.lines.pct from ${SUMMARY}"
  exit 1
fi

# awk handles floating-point comparison portably.
if awk "BEGIN { exit !(${PCT} >= ${THRESHOLD}) }"; then
  echo "::notice::line coverage ${PCT} >= ${THRESHOLD}"
  exit 0
else
  echo "::error::line coverage ${PCT} < ${THRESHOLD}"
  exit 1
fi
