name = "ubm-hyogo-api"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "ubm-hyogo-db-prod"
database_id = "24963f0a-7fbb-4508-a93a-f8e502aa4585"

[env.staging]
name = "ubm-hyogo-api-staging"

[env.staging.vars]
ENVIRONMENT = "staging"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "ubm-hyogo-db-staging"
database_id = "990e5d6c-51eb-4826-9c13-c0ae007d5f46"
